title: Jinhong Jung
logo: /assets/img/profile.jpeg
description: Ph.d. Candidate @ SNU </br> <p><i>The profile picture is tentative, which will be replaced with more recent and academic one later :)</i></p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
