- type: journal
  venue: TKDE
  full-venue: ACM Transactions on Knowledge and Data Engineering
  years: 
    - item:
      year: 2022
      link: 

- type: pcmember
  venue: AAAI
  full-venue: AAAI Conference on Artificial Intelligence
  years: 
    - item:
      year: 2021
      link: https://bit.ly/3rIaXcI
    - item:
      year: 2023
      link: 

- type: pcmember
  venue: TheWebConf
  full-venue: The Web Conference
  years: 
    - item:
      year: 2022
      link: https://www2022.thewebconf.org/program-committee-members/ 
    - item:
      year: 2023
      link: 

- type: pcmember
  venue: WSDM
  full-venue: ACM Conference on Web Search and Data Mining
  years: 
    - item:
      year: 2023
      link: 

- type: pcmember
  venue: BigComp
  full-venue: IEEE Conference on Big Data and Smart Computing
  years: 
    - item:
      year: 2021
      link: http://www.bigcomputing.org/conf2021/program-committee.html

- type: reviewer
  venue: KDD
  full-venue: ACM Conference on Knowledge Discovery and Data Mining
  years: 
    - item:
      year: 2016
      link: 
    - item:
      year: 2017
      link: 
    - item:
      year: 2018
      link: 
    - item:
      year: 2019
      link: 
    - item:
      year: 2020
      link: 

  
- type: reviewer
  venue: TheWebConf
  full-venue: The Web Conference
  years: 
    - item:
      year: 2016
      link: 
    - item:
      year: 2017
      link: 
    - item:
      year: 2018
      link: 
    - item:
      year: 2019
      link: 

- type: reviewer
  venue: ICDM
  full-venue: IEEE Conference on Data Mining
  years: 
    - item:
      year: 2015
      link: 
    - item:
      year: 2018
      link: 
    - item:
      year: 2019
      link: 

- type: reviewer
  venue: WSDM
  full-venue: ACM Conference on Web Search and Data Mining
  years: 
    - item:
      year: 2018
      link: 
    - item:
      year: 2019
      link: 

- type: reviewer
  venue: CIKM
  full-venue: ACM Conference on Information and Knowledge Management
  years: 
    - item:
      year: 2016
      link: 
    - item:
      year: 2017
      link: 
    - item:
      year: 2018
      link: 
    - item:
      year: 2019
      link: 

- type: reviewer
  venue: SAC
  full-venue: ACM Symposium on Applied Computing
  years: 
    - item:
      year: 2016
      link: 
    - item:
      year: 2017
      link: 
    - item:
      year: 2018
      link: 
    - item:
      year: 2019
      link: 
    - item:
      year: 2020
      link: 

- type: reviewer
  venue: ECML/PKDD
  full-venue: "European Conference on Machine Learning and Data Mining"
  years: 
    - item:
      year: 2016
      link: 
    - item:
      year: 2017
      link: 

- type: reviewer
  venue: BigComp
  full-venue: IEEE Conference on Big Data and Smart Computing
  years: 
    - item:
      year: 2016
      link: 
    - item:
      year: 2018
      link: 
    - item:
      year: 2020
      link: 

- type: reviewer
  venue: DSAA
  full-venue: International Conference on Data Science and Advanced Analytics
  years: 
    - item:
      year: 2016
      link: 

- type: reviewer
  venue: BigData
  full-venue: IEEE International Conference on Big Data
  years: 
    - item:
      year: 2016
      link: 

- type: reviewer
  venue: DASFAA
  full-venue: International Conference on Database Systems for Advanced Applications
  years: 
    - item:
      year: 2023
      link: 
